# This file is auto-generated by sqlacodegen after `dbt run`.
# Do not edit manually. Re-generate with:
#   sqlacodegen --generator declarative $DATABASE_URL --outfile storage/models.py
#
# See task 3.8 / 6.1 in tasks.md and the Dagster `sqlalchemy_models` asset.
